name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build and push the image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
  
  update-gitops:
    name: Update GitOps Repository
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout GitOps Repository
      uses: actions/checkout@v2
      with:
        repository: https://github.com/Obiana-Ifeanyi/argo-gitops.git
        ref: main
        token: ${{ secrets.GITOPS_TOKEN }} # GitHub token for authentication
    
    - name: Update GitOps Manifest
      run: |
        # Assuming you update your manifest files here
        cd gitops-repo
        # Replace or update the manifest files, for example:
        sed -i 's/old-image/${{ secrets.DOCKER_USERNAME }}\/my-app:${{ github.sha }}/g' k8s/manifest.yaml
        
    - name: commit and push
      run: |
        # Commit and push the changes
        git config user.name "GitHub Actions"
        git config user.email "ifeanyiobiana@gmail.com"
        git add .
        git commit -m "Update deployment with new image ${GITHUB_SHA}"
        git push origin main

